#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("android.Resource", IsApplication=true)]

namespace android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::android.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int move = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int out_left = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int out_right = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baseline_arrow_drop_down_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IdSpinner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int settings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splashIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int stop_spinner_bg_left = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int stop_spinner_bg_right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int switchIcon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int StopSpinners = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int button1 = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int buttonLeft = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int buttonRight = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int buttonSettings = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int buttonSwitch = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int checkBox1 = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int flipper = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int idSpinnerText = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int layoutTrips = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int loader = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int radioButton1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int radioButton2 = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int radioGroup = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int spinnerFrom = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int spinnerRoute = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int spinnerTo = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int textView0 = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int textViewDate = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int textViewDate1 = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int textViewNoInternet = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int textViewNoLocation = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int StopSpinners = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Trips = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int select_from = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int select_route = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int select_to = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme_Base = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
